const images = {
    logo: require('./logokt.svg'),
    appStore: require('./app-store.svg'),
    chPlay: require('./ch-play.svg'),
    phone: require('./phone.svg'),
    vnLg: require('./vn-lg.webp'),
    engLg: require('./eng-lg.webp'),
    chinaLg: require('./china-lg.webp'),
    hook: require('./hook.svg'),
    threeLine: require('./three-line.svg'),
    circleLine: require('./circle-line.svg'),
    menuBg: require('./menu-bg.webp'),
    menuSsTwo: require('./menu-ss2.webp'),
    menuTarget: require('./menu-target.webp'),
    menuPlan: require('./menu-plan.webp'),
    menuProrgess: require('./menu-progress.webp'),
    menuPolicy: require('./menu-policy.webp'),
    iphone7: require('./iPhone-7.webp'),
    menuReport: require('./menu-report.webp'),
    iconBgSix: require('./icon-bg-six.svg'),
    contact: require('./contact.webp'),
    footerShape: require('./footer-shape.svg'),
    footerShape2: require('./footer-shape2.svg'),
    footerShape3: require('./footer-shape3.svg'),
    avtFeedback1: require('./avtfeedback1.svg'),
    avtFeedback2: require('./avtfeedback2.svg'),
    avtFeedback3: require('./avtfeedback3.svg'),
    loginBg: require('./loginBanner.svg'),
    avtAddNewCompany: require('./addNewCompany.svg'),
    noData: require('./NoData.svg'),
    avtUser: require('./user.png'),
    workSpace: require('./workspace.svg'),
    avtBot: require('./bot.webp'),
    workSpaceC: require('./workspace.png'),
    groupC: require('./group.png'),
    positionC: require('./position.png'),
    mapBase: require('./mapbase.svg'),
    qrCode: require('./qr.png'),
    avtEmployee: require('./avt-employee.png'),
    avtBotMys: require('./avatar-add-personnel.svg'),
    uploadFile: require('./GallerySend.png'),
};

export { images };
